default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker

build:
  stage: build
  tags:
    - shared
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_JOB_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_JOB_ID
    - docker tag $CI_REGISTRY_IMAGE:$CI_JOB_ID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

# NEED TESTS

deploy-test:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Останавливаю старую версию сервиса"
    - if [ "$(docker ps -a -q --filter ancestor=$CI_REGISTRY_IMAGE)" ]; then docker stop $(docker ps -a -q --filter ancestor=$CI_REGISTRY_IMAGE); else echo "Нет запущенных контейнеров для остановки"; fi
    - echo "Удаляю устаревшие образ"
    - if [ "$(docker images --filter -q reference=$CI_REGISTRY_IMAGE)" ]; then docker image remove -f $(docker images --filter -q reference=$CI_REGISTRY_IMAGE); else echo "Нет образов для удаления"; fi
    - echo "Заполняю env файл"
    - cat $ENV_FILE > .env
    - echo "Запускаю новую версию сервиса"
    - docker compose up -d