default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker

  before_script:
    - docker info

build:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_PROJECT_NAME:$CI_JOB_ID .
    - docker tag $CI_PROJECT_NAME:$CI_JOB_ID $CI_PROJECT_NAME:latest
    - docker tag $CI_PROJECT_NAME:$CI_JOB_ID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
