default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker

  before_script:
    - docker info

build:
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $IMAGE_NAME
    - echo $CI_JOB_ID
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $IMAGE_NAME:$CI_CONCURRENT_PROJECT_ID .
#    - docker push $IMAGE_NAME:$CI_CONCURRENT_PROJECT_ID
#    - docker tag $IMAGE_NAME:$CI_CONCURRENT_PROJECT_ID $IMAGE_NAME:latest
#    - docker tag $IMAGE_NAME:$CI_CONCURRENT_PROJECT_ID $CI_REGISTRY_IMAGE:latest
#    - docker push $CI_REGISTRY_IMAGE:latest
