default:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker

build:
  stage: build
  tags:
    - shared
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_JOB_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_JOB_ID
    - docker tag $CI_REGISTRY_IMAGE:$CI_JOB_ID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

# NEED TESTS

deploy-test:
  stage: deploy
  tags:
    - shell
  script:
    - docker compose down conflue
    - docker image remove $(docker images gitlab.teamops.com.ru:5050/teamops/openideasconflue --format {{.ID}})
    - docker compose up conflue -d
