services:
  db:
    image: postgres
    restart: always
    ports:
        - "5433:5432"
    environment:
        POSTGRES_DB: "open-ideas-conflue"
        POSTGRES_USER: "open-ideas"
        POSTGRES_PASSWORD: "12345678"
    volumes:
      - /db-data:/var/lib/postgresql/data
  conflue:
    image: gitlab.teamops.com.ru:5050/teamops/openideasconflue:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db