"""articles

Revision ID: 3b70532302bb
Revises: 6b9acd43a28f
Create Date: 2024-11-23 22:00:59.796181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b70532302bb'
down_revision: Union[str, None] = '6b9acd43a28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file_article', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_article', type_='unique')
    # ### end Alembic commands ###
