"""add file_article relation

Revision ID: 6b9acd43a28f
Revises: 2f2cc0b47a3b
Create Date: 2024-11-23 21:45:43.369632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b9acd43a28f"
down_revision: Union[str, None] = "2f2cc0b47a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_article",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "article", ["id"])
    op.create_unique_constraint(None, "comment", ["id"])
    op.create_unique_constraint(None, "file", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="unique")  # type: ignore
    op.drop_constraint(None, "comment", type_="unique")  # type: ignore
    op.drop_constraint(None, "article", type_="unique")  # type: ignore
    op.drop_table("file_article")
    # ### end Alembic commands ###
