"""edit comments

Revision ID: b29078d6b2c3
Revises: 6b9acd43a28f
Create Date: 2024-11-23 23:20:08.481433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b29078d6b2c3"
down_revision: Union[str, None] = "6b9acd43a28f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("comment", sa.Column("article_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "comment", "article", ["article_id"], ["id"])
    op.create_unique_constraint(None, "file_article", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file_article", type_="unique")
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.drop_column("comment", "article_id")
    op.drop_column("comment", "updated_at")
    # ### end Alembic commands ###
